#!/bin/bash
# Obsidian Daily Note Creator (Auto-increment version)
# Runs daily at 8:30 AM
# Creates new note each day with auto-incremented ID

# Configuration
NOTE_DIR="$HOME/.openclaw/workspace/storage/vault/u_1/note"
MEMORY_FILE="/root/.openclaw/workspace/MEMORY.md"
TODAY=$(date +%Y-%m-%d)
YESTERDAY=$(date -d "yesterday" +%Y-%m-%d)

# Extract todos from MEMORY.md
get_todos() {
    echo "## 📋 待办事项"
    echo ""
    echo "### 🔄 持续进行"
    if [ -f "$MEMORY_FILE" ]; then
        grep -A 30 "待办追踪" "$MEMORY_FILE" 2>/dev/null | grep "^- " | sed 's/^- /- [ ] /' | head -10
    fi
    echo ""
    echo "### 💼 工作任务"
    echo "- [ ] 与 Chapin 跟进数据中台项目进展"
    echo "- [ ] 联系深圳 office 看房需求反馈"
    echo "- [ ] 跟进 SAP 接口开发需求确认"
    echo "- [ ] 用友云端项目进度跟进"
    echo "- [ ] GP% Dashboard 开发（等待 Ken 提供历史数据）"
    echo "- [ ] AR Dashboard 开发（等待汇率数据）"
    echo ""
    echo "### 📊 股票监控"
    echo "- [ ] 检查每日股票分析推送"
    echo ""
}

# Find next available note ID
get_next_note_id() {
    local max_id=0
    for dir in "$NOTE_DIR"/n_*; do
        if [ -d "$dir" ]; then
            local id=$(basename "$dir" | sed 's/n_//')
            if [[ "$id" =~ ^[0-9]+$ ]] && [ "$id" -gt "$max_id" ]; then
                max_id=$id
            fi
        fi
    done
    echo $((max_id + 1))
}

# Check if today's note already exists
check_today_note() {
    local max_id=0
    for dir in "$NOTE_DIR"/n_*; do
        if [ -d "$dir" ]; then
            local id=$(basename "$dir" | sed 's/n_//')
            if [[ "$id" =~ ^[0-9]+$ ]] && [ "$id" -gt "$max_id" ]; then
                max_id=$id
            fi
        fi
    done

    # Check if today's date matches the latest note's date
    local latest_content="${NOTE_DIR}/n_${max_id}/content.txt"
    if [ -f "$latest_content" ] && grep -q "$TODAY" "$latest_content"; then
        echo "$max_id"
    else
        echo "new"
    fi
}

# Create/update note
create_or_update_note() {
    local note_id=$(check_today_note)
    local note_path="${NOTE_DIR}/n_${note_id}/content.txt"

    local content="# ${TODAY}

## 🎯 今日重点

### Morning Review
- [ ] 回顾昨日待办完成情况
- [ ] 查看股票分析推送
- [ ] 确认当日会议安排

$(get_todos)

### 📅 会议安排
待补充...

### 💡 今日灵感/想法
待补充...

---
*Generated by OpenClaw Auto-Note @ $(date '+%Y-%m-%d %H:%M')*"

    if [ "$note_id" == "new" ]; then
        # Create new note
        note_id=$(get_next_note_id)
        note_path="${NOTE_DIR}/n_${note_id}/content.txt"
        mkdir -p "${NOTE_DIR}/n_${note_id}"
        echo "$content" > "$note_path"
        echo "$content" > "${NOTE_DIR}/n_${note_id}/snapshot.txt"
        echo "✅ Created: n_${note_id} for ${TODAY}"
    else
        # Append to existing note
        local existing_content=$(cat "$note_path")
        echo "$existing_content

--- Auto-Note Update ---
$content" > "$note_path"
        echo "✅ Updated: n_${note_id} for ${TODAY}"
    fi
}

create_or_update_note
