#!/bin/bash
# Obsidian Daily Note Creator (API version)
# Runs daily at 8:30 AM
# Creates new note via Fast Note Sync API

# Configuration
MEMORY_FILE="/root/.openclaw/workspace/MEMORY.md"
TODAY=$(date +%Y-%m-%d)
FASTNOTE_URL="http://127.0.0.1:9000"
CREDENTIALS="asa1525:a9940710"

# Login to Fast Note Sync
login_fastnote() {
    local response=$(curl -s "${FASTNOTE_URL}/api/user/login" \
        -X POST \
        -d "credentials=${CREDENTIALS}")
    echo "$response" | grep -o '"token":"[^"]*"' | cut -d'"' -f4
}

# Extract todos from MEMORY.md
get_todos() {
    echo "## 📋 待办事项"
    echo ""
    echo "### 🔄 持续进行"
    if [ -f "$MEMORY_FILE" ]; then
        grep -A 30 "待办追踪" "$MEMORY_FILE" 2>/dev/null | grep "^- " | sed 's/^- /- [ ] /' | head -10
    fi
    echo ""
    echo "### 💼 工作任务"
    echo "- [ ] 与 Chapin 跟进数据中台项目进展"
    echo "- [ ] 联系深圳 office 看房需求反馈"
    echo "- [ ] 跟进 SAP 接口开发需求确认"
    echo "- [ ] 用友云端项目进度跟进"
    echo "- [ ] GP% Dashboard 开发（等待 Ken 提供历史数据）"
    echo "- [ ] AR Dashboard 开发（等待汇率数据）"
    echo ""
    echo "### 📊 股票监控"
    echo "- [ ] 检查每日股票分析推送"
    echo ""
}

# Get next note ID
get_next_note_id() {
    local response=$(curl -s "${FASTNOTE_URL}/api/note?vault=Obsidian%20Vault&path=n_1.md" \
        -H "Authorization: Bearer $(login_fastnote)" 2>/dev/null)
    
    # If n_1.md exists, find max ID
    if echo "$response" | grep -q '"code":1'; then
        # Find max ID by listing notes
        local max_id=0
        for i in $(seq 1 1000); do
            local check=$(curl -s "${FASTNOTE_URL}/api/note?vault=Obsidian%20Vault&path=n_${i}.md" \
                -H "Authorization: Bearer $(login_fastnote)" 2>/dev/null)
            if echo "$check" | grep -q '"code":430'; then
                break
            fi
            max_id=$i
        done
        echo $((max_id + 1))
    else
        echo "1"
    fi
}

# Check if today's note exists
check_today_note() {
    local response=$(curl -s "${FASTNOTE_URL}/api/note/list?vault=Obsidian%20Vault&limit=100" \
        -H "Authorization: Bearer $(login_fastnote)" 2>/dev/null)
    
    # Look for today's note
    if echo "$response" | grep -q "${TODAY}"; then
        echo "found"
    else
        echo "new"
    fi
}

# Create or update note via API
create_or_update_note() {
    local token=$(login_fastnote)
    local today_note_id=""
    
    # Check for existing notes
    local response=$(curl -s "${FASTNOTE_URL}/api/note/list?vault=Obsidian%20Vault&limit=100" \
        -H "Authorization: Bearer $token" 2>/dev/null)
    
    # Find max ID
    local max_id=0
    for i in $(seq 1 1000); do
        local check=$(curl -s "${FASTNOTE_URL}/api/note?vault=Obsidian%20Vault&path=n_${i}.md" \
            -H "Authorization: Bearer $token" 2>/dev/null)
        if echo "$check" | grep -q '"code":430'; then
            break
        fi
        max_id=$i
    done
    
    local next_id=$((max_id + 1))
    
    # Generate content
    local content="# ${TODAY}

## 🎯 今日重点

### Morning Review
- [ ] 回顾昨日待办完成情况
- [ ] 查看股票分析推送
- [ ] 确认当日会议安排

$(get_todos)

### 📅 会议安排
待补充...

### 💡 今日灵感/想法
待补充...

---
*Generated by OpenClaw Auto-Note @ $(date '+%Y-%m-%d %H:%M')*"

    # Create new note via API
    local result=$(curl -s "${FASTNOTE_URL}/api/note" \
        -X POST \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "vault=Obsidian Vault" \
        -d "path=n_${next_id}.md" \
        -d "content=$content")
    
    if echo "$result" | grep -q '"code":1'; then
        echo "✅ Created: n_${next_id} for ${TODAY}"
    else
        echo "❌ Failed to create note: $result"
    fi
}

# Main
create_or_update_note
