#!/bin/bash
# Obsidian Daily Note Creator with Todo List
# Runs daily at 8:30 AM

# Configuration
OBSIDIAN_VAULT="$HOME/.openclaw/workspace/storage/vault/u_1/note"
MEMORY_FILE="/root/.openclaw/workspace/MEMORY.md"
TODAY=$(date +%Y-%m-%d)

# Extract todos from MEMORY.md
get_todos() {
    echo "## 📋 待办事项"
    echo ""
    echo "### 🔄 持续进行"
    if [ -f "$MEMORY_FILE" ]; then
        grep -A 20 "待办追踪" "$MEMORY_FILE" 2>/dev/null | grep "^- " | sed 's/^- /- [ ] /' | head -10
    fi
    echo ""
    echo "### 💼 工作任务"
    echo "- [ ] 与 Chapin 跟进数据中台项目进展"
    echo "- [ ] 联系深圳 office 看房需求反馈"
    echo "- [ ] 跟进 SAP 接口开发需求确认"
    echo "- [ ] 用友云端项目进度跟进"
    echo "- [ ] GP% Dashboard 开发（等待 Ken 提供历史数据）"
    echo "- [ ] AR Dashboard 开发（等待汇率数据）"
    echo ""
    echo "### 📊 股票监控"
    echo "- [ ] 检查每日股票分析推送"
    echo ""
}

# Find next available note number
find_next_note() {
    local max_num=0
    for dir in "$OBSIDIAN_VAULT"/n_*; do
        if [ -d "$dir" ]; then
            local num=$(basename "$dir" | sed 's/n_//')
            if [ "$num" -gt "$max_num" ] 2>/dev/null; then
                max_num=$num
            fi
        fi
    done
    echo $((max_num + 1))
}

# Create the daily note
create_note() {
    local content="# ${TODAY}

## 🎯 今日重点

### Morning Review
- [ ] 回顾昨日待办完成情况
- [ ] 查看股票分析推送
- [ ] 确认当日会议安排

$(get_todos)

### 📅 会议安排
待补充...

### 💡 今日灵感/想法
待补充...

---
*Generated by OpenClaw Auto-Note @ $(date '+%Y-%m-%d %H:%M')*"

    if [ -n "$EXISTING_NOTE" ]; then
        # Append to existing note
        local note_dir=$(dirname "$EXISTING_NOTE")
        local existing_content=$(cat "$EXISTING_NOTE")
        echo "$existing_content

--- Auto-Note Update ---
$content" > "$EXISTING_NOTE"
        echo "✅ Updated: $(basename "$note_dir")"
        echo "   Appended auto-generated todo list"
    else
        # Create new note
        local next_num=$(find_next_note)
        local note_dir="${OBSIDIAN_VAULT}/n_${next_num}"
        mkdir -p "$note_dir"
        echo "$content" > "$note_dir/content.txt"
        echo "$content" > "$note_dir/snapshot.txt"
        echo "✅ Created: n_${next_num}"
    fi
}

# Check if already created today, if so append to existing note
EXISTING_NOTE=$(grep -l "^# ${TODAY}$" "$OBSIDIAN_VAULT"/n_*/content.txt 2>/dev/null | head -1)

# Create the note
create_note

echo "🎯 Daily note created successfully!"
